language: python

cache: pip

os:
  - linux

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install "ipython<6.0"
  - pip install jupyter_client
  - pip install -e . 
  - pip install --only-binary=numpy,scipy numpy scipy

script:
  python setup.py test

after_success: coveralls
