language: python

cache: pip

os:
  - linux

python:
  - 3.5
  - 3.6

matrix:
    allow_failures:
        - python: 3.5
    include:
        - python: 3.7
          dist: xenial
          sudo: true

install:
  - pip install -e .
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install coveralls
  - pip install pytest

script:
  - pip install "git+https://github.com/zfit/zfit.git@develop"
  - coverage run --source=statnight setup.py test

after_success: coveralls
