language: python

cache: pip

os:
  - linux

python:
  - 3.4
  - 3.5
  - 3.6

matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

install:
  - pip install -e .
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install coveralls
  - pip install pytest

script:
  coverage run --source=statnight setup.py test

after_success: coveralls
