language: python

cache: pip

os:
  - linux

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -e .
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install coveralls
  - pip install pytest

script:
  python setup.py test

after_success: coveralls
